export const pinCodeData = [
    { "pinCode": "110001", "city": "New Delhi", "district": "Central Delhi", "state": "Delhi" },
    { "pinCode": "110002", "city": "New Delhi", "district": "Central Delhi", "state": "Delhi" },
    { "pinCode": "110003", "city": "New Delhi", "district": "Central Delhi", "state": "Delhi" },
    { "pinCode": "110004", "city": "New Delhi", "district": "Central Delhi", "state": "Delhi" },
    { "pinCode": "110005", "city": "New Delhi", "district": "Central Delhi", "state": "Delhi" },
    { "pinCode": "400001", "city": "Mumbai", "district": "Mumbai City", "state": "Maharashtra" },
    { "pinCode": "400002", "city": "Mumbai", "district": "Mumbai City", "state": "Maharashtra" },
    { "pinCode": "400003", "city": "Mumbai", "district": "Mumbai City", "state": "Maharashtra" },
    { "pinCode": "400004", "city": "Mumbai", "district": "Mumbai City", "state": "Maharashtra" },
    { "pinCode": "400005", "city": "Mumbai", "district": "Mumbai City", "state": "Maharashtra" },
    { "pinCode": "600001", "city": "Chennai", "district": "Chennai", "state": "Tamil Nadu" },
    { "pinCode": "600002", "city": "Chennai", "district": "Chennai", "state": "Tamil Nadu" },
    { "pinCode": "600003", "city": "Chennai", "district": "Chennai", "state": "Tamil Nadu" },
    { "pinCode": "600004", "city": "Chennai", "district": "Chennai", "state": "Tamil Nadu" },
    { "pinCode": "600005", "city": "Chennai", "district": "Chennai", "state": "Tamil Nadu" },
    { "pinCode": "700001", "city": "Kolkata", "district": "Kolkata", "state": "West Bengal" },
    { "pinCode": "700002", "city": "Kolkata", "district": "Kolkata", "state": "West Bengal" },
    { "pinCode": "700003", "city": "Kolkata", "district": "Kolkata", "state": "West Bengal" },
    { "pinCode": "700004", "city": "Kolkata", "district": "Kolkata", "state": "West Bengal" },
    { "pinCode": "700005", "city": "Kolkata", "district": "Kolkata", "state": "West Bengal" },
    { "pinCode": "500001", "city": "Hyderabad", "district": "Hyderabad", "state": "Telangana" },
    { "pinCode": "500002", "city": "Hyderabad", "district": "Hyderabad", "state": "Telangana" },
    { "pinCode": "500003", "city": "Hyderabad", "district": "Hyderabad", "state": "Telangana" },
    { "pinCode": "500004", "city": "Hyderabad", "district": "Hyderabad", "state": "Telangana" },
    { "pinCode": "500005", "city": "Hyderabad", "district": "Hyderabad", "state": "Telangana" },
    { "pinCode": "110006", "city": "New Delhi", "district": "Central Delhi", "state": "Delhi" },
    { "pinCode": "110007", "city": "New Delhi", "district": "Central Delhi", "state": "Delhi" },
    { "pinCode": "110008", "city": "New Delhi", "district": "Central Delhi", "state": "Delhi" },
    { "pinCode": "110009", "city": "New Delhi", "district": "Central Delhi", "state": "Delhi" },
    { "pinCode": "110010", "city": "New Delhi", "district": "Central Delhi", "state": "Delhi" },
    { "pinCode": "400006", "city": "Mumbai", "district": "Mumbai City", "state": "Maharashtra" },
    { "pinCode": "400007", "city": "Mumbai", "district": "Mumbai City", "state": "Maharashtra" },
    { "pinCode": "400008", "city": "Mumbai", "district": "Mumbai City", "state": "Maharashtra" },
    { "pinCode": "400009", "city": "Mumbai", "district": "Mumbai City", "state": "Maharashtra" },
    { "pinCode": "400010", "city": "Mumbai", "district": "Mumbai City", "state": "Maharashtra" },
    { "pinCode": "600006", "city": "Chennai", "district": "Chennai", "state": "Tamil Nadu" },
    { "pinCode": "600007", "city": "Chennai", "district": "Chennai", "state": "Tamil Nadu" },
    { "pinCode": "600008", "city": "Chennai", "district": "Chennai", "state": "Tamil Nadu" },
    { "pinCode": "600009", "city": "Chennai", "district": "Chennai", "state": "Tamil Nadu" },
    { "pinCode": "600010", "city": "Chennai", "district": "Chennai", "state": "Tamil Nadu" },
    { "pinCode": "700006", "city": "Kolkata", "district": "Kolkata", "state": "West Bengal" },
    { "pinCode": "700007", "city": "Kolkata", "district": "Kolkata", "state": "West Bengal" },
    { "pinCode": "700008", "city": "Kolkata", "district": "Kolkata", "state": "West Bengal" },
    { "pinCode": "700009", "city": "Kolkata", "district": "Kolkata", "state": "West Bengal" },
    { "pinCode": "700010", "city": "Kolkata", "district": "Kolkata", "state": "West Bengal" },
    { "pinCode": "500006", "city": "Hyderabad", "district": "Hyderabad", "state": "Telangana" },
    { "pinCode": "500007", "city": "Hyderabad", "district": "Hyderabad", "state": "Telangana" },
    { "pinCode": "500008", "city": "Hyderabad", "district": "Hyderabad", "state": "Telangana" },
    { "pinCode": "500009", "city": "Hyderabad", "district": "Hyderabad", "state": "Telangana" },
    { "pinCode": "500010", "city": "Hyderabad", "district": "Hyderabad", "state": "Telangana" },
    { "pinCode": "900001", "city": "Jaipur", "district": "Jaipur", "state": "Rajasthan" },
    { "pinCode": "900002", "city": "Jaipur", "district": "Jaipur", "state": "Rajasthan" },
    { "pinCode": "900003", "city": "Jaipur", "district": "Jaipur", "state": "Rajasthan" },
    { "pinCode": "900004", "city": "Jaipur", "district": "Jaipur", "state": "Rajasthan" },
    { "pinCode": "900005", "city": "Jaipur", "district": "Jaipur", "state": "Rajasthan" }
  ]
  